'use strict';
const T=window.Triangle,$=s=>document.querySelector(s),KEY='triangle-lab-v1';
let review=false,currentView='lab',last=null;
const fresh=()=>({total:0,covered:[],found:{},history:[]});let state=fresh();
try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&Number.isSafeInteger(s.total)&&s.total>=0&&Array.isArray(s.covered)&&s.found&&typeof s.found==='object'&&Array.isArray(s.history)){state={total:s.total,covered:s.covered.filter(x=>T.cases.some(c=>c.id===x)),found:Object.fromEntries(Object.entries(s.found).filter(([id,r])=>T.bugs.some(b=>b.id===id)&&r&&Array.isArray(r.input))),history:s.history.filter(r=>r&&Array.isArray(r.input)&&T.labels[r.actual]&&T.labels[r.expected]).slice(0,500)};}}catch{ $('#storage-warning').hidden=false; }
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{$('#storage-warning').hidden=false;}}
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
const fields=['#side-a','#side-b','#side-c'].map($);
Object.entries(T.labels).forEach(([v,label])=>{const o=el('option','',label);o.value=v;$('#expected').append(o);});
function builds(){const selected=$('#build').value;$('#build').replaceChildren();T.bugs.forEach((b,i)=>{const o=el('option','',`Сборка ${String(i+1).padStart(2,'0')}${review?' — '+b.title:''}${state.found[b.id]?' · баг найден':''}`);o.value=b.id;$('#build').append(o);});const o=el('option','','Эталон · без намеренных дефектов');o.value='reference';$('#build').append(o);if(selected)$('#build').value=selected;}
function buildName(id){const i=T.bugs.findIndex(b=>b.id===id);return i<0?'Эталон':`Сборка ${String(i+1).padStart(2,'0')}`;}
function check(input,expected,build){const actual=T.actual(input,build),oracle=T.oracle(input);let verdict=expected===oracle?(actual===oracle?'pass':'fail'):'wrong';const r={id:state.total+1,time:new Date().toISOString(),input:[...input],build,expected,actual,oracle,verdict};state.total++;state.covered=[...new Set([...state.covered,...T.coverage(input)])];if(verdict==='fail'&&build!=='reference'&&!state.found[build])state.found[build]=r;state.history.unshift(r);state.history=state.history.slice(0,500);return r;}
function showResult(r){last=r;$('#actual-result').textContent=T.labels[r.actual];$('#result-badge').textContent=buildName(r.build).toUpperCase();$('#result-note').textContent='Это ответ тестируемой программы. Он может содержать ошибку.';const shape=$('#triangle-shape');shape.style.display=['invalid','none'].includes(r.actual)?'none':'';shape.setAttribute('points',r.actual==='equilateral'?'110,196 310,196 210,23':r.actual==='isosceles'?'95,196 325,196 210,40':'80,196 340,196 174,38');$('#diagram-label').textContent=['invalid','none'].includes(r.actual)?'НЕТ СХЕМЫ ДЛЯ ЭТОГО ОТВЕТА':'ПО ОТВЕТУ СБОРКИ · НЕ В МАСШТАБЕ';const box=$('#comparison');box.hidden=false;box.className=r.verdict==='fail'?'bad':r.verdict==='pass'?'good':'';box.textContent=r.verdict==='fail'?'Баг подтверждён. Ожидалось: '+T.labels[r.oracle]+'. Пример сохранён в найденных дефектах.':r.verdict==='pass'?'Ожидание подтвердилось. На этих данных результат верный.':'Пересмотри ожидание: оно не соответствует спецификации. Баг пока не засчитан.';if(review&&r.verdict==='wrong')box.textContent+=' По спецификации: '+T.labels[r.oracle]+'.';}
function table(target,rows){target.replaceChildren();if(!rows.length){target.append(el('div','empty','Проверок пока нет. Начни с трёх сторон и своего ожидания.'));return;}const table=el('table'),thead=el('thead'),tr=el('tr');['№ / сборка','Стороны A · B · C','Ожидание','Результат','Итог'].forEach(x=>tr.append(el('th','',x)));thead.append(tr);table.append(thead);const body=el('tbody');for(const r of rows){const tr=el('tr');[`${r.id} / ${buildName(r.build)}`,r.input.map(x=>JSON.stringify(x)).join(' · '),T.labels[r.expected],T.labels[r.actual]].forEach(x=>tr.append(el('td','',x)));const td=el('td'), badge=el('span','status '+(r.verdict==='pass'?'pass':r.verdict==='fail'?'fail':'neutral'),r.verdict==='pass'?'Совпало':r.verdict==='fail'?'Баг найден':'Проверь ожидание');td.append(badge);tr.append(td);body.append(tr);}table.append(body);target.append(table);}
function renderCases(){const list=$('#case-list');list.replaceChildren();T.cases.forEach((c,i)=>{const done=state.covered.includes(c.id),card=el('article','case-card'+(done?' found':''));const row=el('div','badge-row');row.append(el('small','',`TC-${String(i+1).padStart(2,'0')} · ${c.group}`),el('small','',done?'Проверено':'Не проверено'));card.append(row,el('h3','',c.title));if(review){card.append(el('code','',c.input.map(x=>JSON.stringify(x)).join(' · ')),el('p','','Ожидается: '+T.labels[c.expected]));const btn=el('button','quiet','Подставить в форму');btn.onclick=()=>{fill(c.input,c.expected);switchView('lab');fields[0].focus();};card.append(btn);}else card.append(el('p','',done?'Категория покрыта твоими данными.':'Подбери значения для этой категории.'));list.append(card);});}
function renderBugs(){const list=$('#bug-list');list.replaceChildren();T.bugs.forEach((b,i)=>{const found=state.found[b.id],card=el('article','case-card'+(found?' found':''));card.append(el('small','',buildName(b.id)+' · '+(found?'Обнаружен':'Не найден')),el('h3','',found||review?b.title:'Скрытый дефект'));if(found||review){card.append(el('p','',b.why));const r=found||{input:b.sample,oracle:T.oracle(b.sample),actual:T.actual(b.sample,b.id)};card.append(el('code','',r.input.map(x=>JSON.stringify(x)).join(' · ')),el('p','','Ожидается: '+T.labels[r.oracle]+'. Получено: '+T.labels[r.actual]+'.'));const btn=el('button','quiet','Воспроизвести');btn.onclick=()=>{$('#build').value=b.id;fill(r.input,r.oracle);switchView('lab');fields[0].focus();};card.append(btn);}else card.append(el('p','','Выбери эту сборку и попробуй нарушить её логику.'));list.append(card);});}
function render(){const found=Object.keys(state.found).length;$('#bug-count').textContent=found;$('#nav-bugs').textContent=found;$('#bug-progress').value=found;$('#case-count').textContent=state.covered.length;$('#case-progress').value=state.covered.length;$('#run-count').textContent=state.total;$('#session-status').textContent=found===9?'Все 9 дефектов обнаружены!':'Каждая проверка — новая гипотеза';builds();table($('#recent'),state.history.slice(0,4));table($('#history'),state.history);renderCases();renderBugs();$('#export').disabled=!state.history.length;$('#run-suite').hidden=!review;$('#teacher').textContent=review?'Вернуться к практике':'Режим разбора';}
const titles={lab:['Проверяй. Сомневайся.','Находи ошибки.','Три стороны. Простая форма. Не всё так однозначно.'],cases:['Тест-кейсы','От классов к границам.','36 категорий для системного исследования программы.'],bugs:['Найденные баги','Докажи каждый.','Воспроизводящие примеры и объяснения дефектов.'],history:['Журнал проверок','Каждая гипотеза учтена.','Сравнивай ожидания и результаты. Сохраняй отчёт.'],spec:['Спецификация','Сначала договоримся.','Верный результат определяется требованиями.']};
function switchView(v){currentView=v;document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!=='view-'+v);document.querySelectorAll('.nav').forEach(x=>{x.classList.toggle('active',x.dataset.view===v);if(x.dataset.view===v)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});const [a,b,d]=titles[v];$('#page-title').replaceChildren(document.createTextNode(a),el('br'),el('span','',b));$('#page-description').textContent=d;}
function fill(input,expected=''){input.forEach((v,i)=>fields[i].value=v);$('#expected').value=expected;$('#expected').setCustomValidity('');}
$('#triangle-form').onsubmit=e=>{e.preventDefault();const expected=$('#expected').value;if(!expected){$('#expected').setCustomValidity('Выбери ожидаемый результат перед проверкой.');$('#expected').reportValidity();return;}$('#expected').setCustomValidity('');const r=check(fields.map(x=>x.value),expected,$('#build').value);save();render();showResult(r);};
$('#expected').onchange=()=>$('#expected').setCustomValidity('');
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));document.querySelectorAll('[data-example]').forEach(b=>b.onclick=()=>{fill(b.dataset.example.split(','));fields[0].focus();});$('#clear-fields').onclick=()=>{fill(['','','']);fields[0].focus();};
let confirmAction=null;function ask(title,message,fn){$('#dialog-title').textContent=title;$('#dialog-text').textContent=message;confirmAction=fn;$('#confirm-dialog').showModal();$('#dialog-cancel').focus();}$('#dialog-cancel').onclick=()=>$('#confirm-dialog').close();$('#dialog-ok').onclick=()=>{$('#confirm-dialog').close();confirmAction?.();};
$('#teacher').onclick=()=>{if(review){review=false;render();if(last)showResult(last);return;}ask('Открыть разбор?','Будут видны входные данные, правильные ответы и все скрытые дефекты. Это режим для преподавателя и самопроверки.',()=>{review=true;render();if(last)showResult(last);});};
$('#run-suite').onclick=()=>{const build=$('#build').value;ask('Запустить учебный набор?','Все 36 кейсов будут выполнены на '+buildName(build)+'. Результаты попадут в журнал и изменят прогресс.',()=>{let r;T.cases.forEach(c=>r=check(c.input,c.expected,build));save();render();showResult(r);switchView('history');});};
$('#reset').onclick=()=>ask('Сбросить весь прогресс?','История, покрытые категории и найденные баги будут удалены из этого браузера.',()=>{state=fresh();last=null;save();render();$('#comparison').hidden=true;$('#actual-result').textContent='Какой получится треугольник?';$('#result-note').textContent='Введи три стороны и проверь свою гипотезу.';$('#result-badge').textContent='ОЖИДАЕТ ВВОДА';$('#triangle-shape').style.display='';$('#triangle-shape').setAttribute('points','80,196 340,196 174,38');$('#diagram-label').textContent='СХЕМА · НЕ В МАСШТАБЕ';});
function csvCell(v){let s=String(v??'');if(/^[\s]*[=+\-@]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
$('#export').onclick=()=>{const rows=[['Номер','Время UTC','Сборка','A','B','C','Ожидание студента','Фактический результат','Итог',...(review?['По спецификации']:[])],...state.history.map(r=>[r.id,r.time,buildName(r.build),...r.input,T.labels[r.expected],T.labels[r.actual],r.verdict==='fail'?'Баг':r.verdict==='pass'?'Совпало':'Неверное ожидание',...(review?[T.labels[r.oracle]]:[])])];const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='triangle-lab-report.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
render();switchView('lab');
